### ISSUE TITLE
Wrapping up local dev environment to make it available to external parties

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/protocol-contracts#224]
Local dev environment has been implemented to https://github.com/zeta-chain/protocol-contracts/pull/202

The goal of this issue is to wrap up the current environment to make it already promotable and usable for external devs.

- Check the command output and ensure it is DevEx friendly (show what contract to interact with etc...)
- Add documentation, specs and diagrams in the source code
- Add an example contract in the docs (can be the contract we have in integration test that interact with Uniswap for example)

cc @fadeev if you have any inputs

**Comment by fadeev** [comment]
https://github.com/zeta-chain/protocol-contracts/issues/225

**Comment by fadeev** [comment]
I propose we:

* Migrate this into a separate repo and publish on npm. App devs shouldn't ever need to directly clone the protocol contracts repo and start processes from it. Their developer experience includes the template and example contracts.
* Modify the template:
  * import the localnet, have it as a script in package.json. So that you can clone a template and start the localnet.
* Modify the tookit:
  *  code generation to [not throw an error](https://github.com/zeta-chain/toolkit/blob/0113af5e1b0f6fa028039c26e8f8af973134db71/packages/tasks/templates/omnichain/tasks/deploy.ts.hbs#L8-L12) when you're deploying a contract to a network other than zeta_testnet or zeta_mainnet.

Ideally, all the helpers in the toolkit work with localnet, but that may be a larger refactoring.

As a quick workaround, we can modify the deploy and interact task to accept custom system contract/gateway addresses.

**Comment by fadeev** [comment]
Localnet is designed for the new architecture with Gateway.

What if we introduced `npx hardhat universal` that will generate a universal app template that be compatible with compatible with localnet as well as testnet/mainnet when it's shipped.

**Comment by lumtis** [comment]
I agree on the idea to have the functionality available published on NPM and not having to clone this repo. I think as a first step we could introduce a read me here to provide some info to test the contract

> that is compatible with localnet as well as testnet/mainnet when it's shipped.

What do you mean by compatible, the app is scaffolded with a script to deploy the smart contract to the localnet, and to a live network?

**Comment by fadeev** [comment]
@lumtis I mean the current `npx hardhat omnichain` generates a contract and HH tasks for interacting with the contract using TSS and custody contract. We can keep it right now, because that's how it works on the live network.

I propose adding `npx hardhat universal` that is compatible with Gateway and will eventually replace the `omnichain` command. Since Gateway is not on testnet yet, this will also be an opportunity to make the `deploy`/`interact` tasks compatible with localnet.

**Comment by lumtis** [comment]
We now have localnet
